apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lijcam/tailspin-argocd-cd
    targetRevision: main
  destination:
    namespace: web-app
    server: https://api.pra8b51q.australiacentral.aroapp.io:6443
